### PR TITLE
#165 support for Graylog 5 and notification type unsupported fixed

### PR DESCRIPTION
**Pull request by unbearables**
## Related Issues
#165 

## Description
- Upgraded to Graylog 5
- fixed notification type unsupported.
- upgraded other libraries

## Screenshot (if any)
no change on FE

@hidapple  pls review and if you approve this also release new version (or I can do it) - I suggest to go for 2.1.0 version

### CODE REVIEW

**Comment by unbearables** [comment]
Basically my motivation for this plugin is using it for Graylog 5. Although Graylog 5 supports MS Teams notifications, it does not provide `Graylog URL` and `Proxy settings`

**Comment by hidapple** [comment]
@unbearables
I'm really sorry for being too late to review your pull-request.
And thank you for contributing my project! your changes looks good to me.

Going to 2.1.0 seems ok to me.
If you can be a collaborator of this repo to release new version, I will add you.

**Comment by unbearables** [comment]
Yes please add me. I will create new release once I have the time. In the meantime please merge this PR (or I will do it myself after I become maintainer here).

**Review by hidapple — APPROVED** [review]
Thanks
I've just invited you as collaborator.

**Pull request merged**
